image: Visual Studio 2017
build_script:
- cmd: dotnet publish TaskSchedulerCore/TaskSchedulerCore.csproj
- cmd: dotnet publish TaskSchedulerDataBase\TaskSchedulerDataBase.csproj
- msbuild TaskScedulerDemoApp\TaskScedulerDemoApp.csproj /p:Configuration=Release